<?xml version="1.0" encoding="utf-8"?>

<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

	<xsl:import href="metadata.xslt"/>
	<xsl:output method="text" encoding="us-ascii"/>

	<xsl:template name="packagedir">package</xsl:template>
	<xsl:template name="sevenzip">tools\7z.exe</xsl:template>

	<!-- Note that the whitespace in the .bat snippet below is important! -->
	<xsl:template match="information" xml:space="preserve">REM This file is automatically generated from package.xslt and information.xml.
REM Do not edit.

REM This must be run from the $(SolutionDir)!

<!-- Convenient for debugging -->
@echo on

mkdir "<xsl:call-template name="packagedir"/>"

del "<xsl:call-template name="packagedir"/>\<xsl:call-template name="binaryzipfile"/>"

cd Release
"..\<xsl:call-template name="sevenzip"/>" a -tzip "..\<xsl:call-template name="packagedir"/>\<xsl:call-template name="binaryzipfile"/>"<xsl:for-each select="binaryfiles/file"> "<xsl:value-of select="."/>"</xsl:for-each>
if errorlevel 1 goto :oops
cd ..
rmdir /S /Q temp

del "<xsl:call-template name="packagedir"/>\<xsl:call-template name="sourcezipfile"/>"
"<xsl:call-template name="sevenzip"/>" a -tzip "<xsl:call-template name="packagedir"/>\<xsl:call-template name="sourcezipfile"/>"<xsl:for-each select="sourcefiles/file"> "<xsl:value-of select="."/>"</xsl:for-each>
if errorlevel 1 goto :oops

goto :done

:oops
echo Some kind of error occurred when creating distribution ZIPs

:done
</xsl:template>

</xsl:stylesheet>
