#define APPLICATION_TITLE            "Taekwindow"
#define APPLICATION_AUTHOR           "Thomas ten Cate"
#define APPLICATION_AUTHOR_FULL      "Thomas ten Cate <ttencate+taekwindow@gmail.com>"
#define APPLICATION_COPYRIGHT        "Copyright (C) 2006-2007, Thomas ten Cate"
// NOTE: APPLICATION_VERSION and APPLICATION_VERSION_STRING must have four components, probably
#define APPLICATION_VERSION          0,2,0,0
#define APPLICATION_VERSION_STRING   "0.2.0.0"
#define APPLICATION_VERSION_FILENAME 0.2
#define APPLICATION_WEBSITE          "http://taekwindow.sf.net/"
#define APPLICATION_EMAIL            "ttencate+taekwindow@gmail.com"

// File must end with an empty line
