<?xml version="1.0" encoding="utf-8"?>

<stylesheet version="1.0" xmlns="http://www.w3.org/1999/XSL/Transform">

	<import href="../meta.xslt"/>
	<output method="text" encoding="us-ascii"/>

	<variable name="files" select="document('files.xml')/files"/>
	<variable name="binaryfiles" select="$files/binaryfiles"/>
	<variable name="sourcefiles" select="$files/sourcefiles"/>
	<variable name="releasedir" select="$files/releasedir"/>
	<variable name="packagedir" select="$files/packagedir"/>
	<variable name="sevenzip" select="$files/sevenzip"/>

	<!-- Note that the whitespace in the .bat snippet below is important! -->
	<template match="/" xml:space="preserve">
		REM This file is automatically generated from package.bat.xslt. Do not edit.

		REM This must be run from the $(SolutionDir)!

		@echo on

		del "<value-of select="$packagedir"/>\<value-of select="$binaryzipfile"/>"

		cd <value-of select="$releasedir"/>
		"..\..\<value-of select="$sevenzip"/>" a -tzip -mx9 "..\..\<value-of select="$packagedir"/>\<value-of select="$binaryzipfile"/>" <for-each select="$binaryfiles/file"> "<value-of select="."/>"</for-each>
		if errorlevel 1 goto :oops
		cd ..\..

		del "<value-of select="$packagedir"/>\<value-of select="$sourcezipfile"/>"
		"<value-of select="$sevenzip"/>" a -tzip -mx9 "<value-of select="$packagedir"/>\<value-of select="$sourcezipfile"/>" <for-each select="$sourcefiles/file"> "<value-of select="."/>"</for-each>
		if errorlevel 1 goto :oops

		goto :done

		:oops
		echo Some kind of error occurred when creating distribution ZIPs

		:done
	</template>

</stylesheet>
