#ifndef PACKAGE_H
#define PACKAGE_H

#include "../meta.h"

#if APPLICATION_BUILD > 0
#define APPLICATION_VERSION_FILENAME  QUOTEVAL(APPLICATION_MAJOR_VERSION.APPLICATION_MINOR_VERSION.APPLICATION_REVISION.APPLICATION_BUILD)
#elif APPLICATION_REVISION > 0
#define APPLICATION_VERSION_FILENAME  QUOTEVAL(APPLICATION_MAJOR_VERSION.APPLICATION_MINOR_VERSION.APPLICATION_REVISION)
#else
#define APPLICATION_VERSION_FILENAME  QUOTEVAL(APPLICATION_MAJOR_VERSION.APPLICATION_MINOR_VERSION)
#endif

#define RELEASEDIR out\Release
#define PACKAGEDIR 

#endif
