#include "package.h"

/* The comment below is obviously not true if you're reading package.bat.pp right now. */
REM This file is automatically generated from package.bat.pp.
REM Do not edit.

REM This must be run from the $(SolutionDir)!

/* Convenient for debugging */
@echo on

del BINARY_ZIP_FILE_ABS

cd OUTDIR
SEVENZIP a -tzip -mx9 BINARY_ZIP_FILE_ABS <xsl:for-each select="binaryfiles/file"> "<xsl:value-of select="."/>"</xsl:for-each>
if errorlevel 1 goto :oops
cd ..\..
rmdir /S /Q temp

del SOURCE_ZIP_FILE_ABS
SEVENZIP a -tzip -mx9 SOURCE_ZIP_FILE_ABS <xsl:for-each select="sourcefiles/file"> "<xsl:value-of select="."/>"</xsl:for-each>
if errorlevel 1 goto :oops

goto :done

:oops
echo Some kind of error occurred when creating distribution ZIPs

:done
