#ifndef PACKAGE_H
#define PACKAGE_H

#include "../meta.h"

#define QUOTE(x)     #x
#define QUOTE_VAL(x) QUOTE(x)

#if APPLICATION_BUILD > 0
#define APPLICATION_VERSION_FILENAME  QUOTEVAL(APPLICATION_MAJOR_VERSION.APPLICATION_MINOR_VERSION.APPLICATION_REVISION.APPLICATION_BUILD)
#elif APPLICATION_REVISION > 0
#define APPLICATION_VERSION_FILENAME  QUOTEVAL(APPLICATION_MAJOR_VERSION.APPLICATION_MINOR_VERSION.APPLICATION_REVISION)
#else
#define APPLICATION_VERSION_FILENAME  QUOTEVAL(APPLICATION_MAJOR_VERSION.APPLICATION_MINOR_VERSION)
#endif

#define OUTDIR               out\Release
#define PACKAGEDIR           OUTDIR

#define ZIP_BASENAME         MAIN_EXE_FILE
#define BINARY_ZIP_FILE      ZIP_BASENAME-APPLICATION_VERSION_FILENAME.zip
#define BINARY_ZIP_FILE_ABS  OUTDIR\BINARY_ZIP_FILE
#define SOURCE_ZIP_FILE      ZIP_BASENAME-APPLICATION_VERSION_FILENAME-src.zip
#define SOURCE_ZIP_FILE_ABS  OUTDIR\SOURCE_ZIP_FILE

#define SEVENZIP_FILE        7za.exe
#define SEVENZIP             ..\..\SEVENZIP_FILE

#endif
